const Meta = ({ meta }: any) => {
  if (!meta)
    return (
      <>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </>
    )
  return <>{meta}</>
}

export { Meta }
